// Command skillhashes writes cmd/skill_hashes.go: for each bundled skill, the
// sha256 of every SKILL.md version that has been on main, plus the one in the
// working tree. `plivo skill update` replaces an installed copy only when its
// hash is listed; any other content is the user's own edit and is kept.
//
// Run it from the repository root with `make skill-hashes`, after
// `git fetch origin`, whenever a SKILL.md changes. TestSkillHashes fails until
// the bundled version is listed.
//
// Hashes are of the content with CRLF line endings read as LF, the same
// digest the command computes, so a Windows checkout hashes like any other.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
	"strings"
)

// skills maps each bundled skill's source file to the folder it installs
// into, which is what `skill update` finds on disk. Keep in step with
// bundledSkills in cmd/skill.go; TestSkillHashes catches a missing entry.
var skills = []struct{ src, dir string }{
	{"cli-skill/SKILL.md", "plivo-cli"},
	{"audio-streaming-skill/SKILL.md", "plivo-audio-streaming"},
	{"sip-trunking-skill/SKILL.md", "plivo-sip-trunking"},
	{"voice-xml-skill/SKILL.md", "plivo-voice-xml"},
}

func main() {
	ref := flag.String("ref", "origin/main", "branch whose history counts as shipped")
	out := flag.String("o", "cmd/skill_hashes.go", "output Go file")
	flag.Parse()

	var b strings.Builder
	b.WriteString("// Code generated by `make skill-hashes`; DO NOT EDIT.\n\n")
	b.WriteString("package cmd\n\n")
	b.WriteString("// shippedSkillHashes lists, per install folder, the sha256 of every SKILL.md\n")
	b.WriteString("// version that has been on main, plus the bundled one (CRLF read as LF).\n")
	b.WriteString("var shippedSkillHashes = map[string][]string{\n")
	total := 0
	for _, s := range skills {
		sums, err := history(*ref, s.src)
		if err != nil {
			fail(err)
		}
		current, err := os.ReadFile(s.src)
		if err != nil {
			fail(err)
		}
		sums[digest(current)] = true

		sorted := make([]string, 0, len(sums))
		for h := range sums {
			sorted = append(sorted, h)
		}
		sort.Strings(sorted)
		fmt.Fprintf(&b, "\t%q: {\n", s.dir)
		for _, h := range sorted {
			fmt.Fprintf(&b, "\t\t%q,\n", h)
		}
		b.WriteString("\t},\n")
		total += len(sorted)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d hashes from %s)\n", *out, total, *ref)
}

// history returns the digest of every version of path in ref's history.
// --full-history keeps commits on merged branches that history
// simplification would skip.
func history(ref, path string) (map[string]bool, error) {
	revs, err := git("rev-list", "--full-history", ref, "--", path)
	if err != nil {
		return nil, err
	}
	sums := map[string]bool{}
	for _, rev := range strings.Fields(string(revs)) {
		obj := rev + ":" + path
		// The commit that deletes the file lists it but no longer holds it.
		if exec.Command("git", "cat-file", "-e", obj).Run() != nil {
			continue
		}
		blob, err := git("cat-file", "blob", obj)
		if err != nil {
			return nil, err
		}
		sums[digest(blob)] = true
	}
	if len(sums) == 0 {
		return nil, fmt.Errorf("no versions of %s in %s; run `git fetch origin` first", path, ref)
	}
	return sums, nil
}

func git(args ...string) ([]byte, error) {
	out, err := exec.Command("git", args...).Output()
	if err != nil {
		return nil, fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return out, nil
}

// digest matches skillDigest in cmd/skill.go.
func digest(b []byte) string {
	sum := sha256.Sum256(bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n")))
	return hex.EncodeToString(sum[:])
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "skillhashes:", err)
	os.Exit(1)
}
