// Command gendocs renders the public Plivo CLI command tree to a single
// Markdown reference file. Run via `make docs`. It depends only on the cmd
// package and cobra (no extra modules), so it adds nothing to the shipped
// binary's dependency graph.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/plivo/plivo-cli/cmd"
	"github.com/spf13/cobra"
)

func main() {
	out := flag.String("o", "docs/COMMANDS.md", "output Markdown file")
	flag.Parse()

	var cmds []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if c.Name() == "help" || c.Name() == "completion" || c.Hidden {
			return
		}
		cmds = append(cmds, c)
		for _, ch := range c.Commands() {
			walk(ch)
		}
	}
	walk(cmd.Root())
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].CommandPath() < cmds[j].CommandPath() })

	var b strings.Builder
	b.WriteString("# Plivo CLI — command reference\n\n")
	b.WriteString("_Generated by `make docs` from the CLI's own command tree. Do not edit by hand._\n\n")
	b.WriteString("## Commands\n\n")
	for _, c := range cmds {
		path := c.CommandPath()
		anchor := strings.ReplaceAll(path, " ", "-")
		b.WriteString(fmt.Sprintf("- [`%s`](#%s) — %s\n", path, anchor, c.Short))
	}
	b.WriteString("\n")
	for _, c := range cmds {
		writeCmd(&b, c)
	}

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d commands)\n", *out, len(cmds))
}

func writeCmd(b *strings.Builder, c *cobra.Command) {
	b.WriteString("---\n\n")
	b.WriteString("## `" + c.CommandPath() + "`\n\n")
	if c.Short != "" {
		b.WriteString(c.Short + "\n\n")
	}
	if c.Long != "" && c.Long != c.Short {
		b.WriteString(c.Long + "\n\n")
	}

	usage := strings.TrimSpace(c.UseLine())
	if usage != "" {
		fenced := usage
		if c.HasAvailableSubCommands() {
			fenced += "\n" + c.CommandPath() + " [command]"
		}
		b.WriteString("```\n" + fenced + "\n```\n\n")
	}

	if c.Example != "" {
		b.WriteString("Examples:\n\n```\n" + strings.TrimRight(c.Example, "\n") + "\n```\n\n")
	}

	if len(c.Aliases) > 0 {
		quoted := make([]string, len(c.Aliases))
		for i, a := range c.Aliases {
			quoted[i] = "`" + a + "`"
		}
		b.WriteString("Aliases: " + strings.Join(quoted, ", ") + "\n\n")
	}

	if c.HasAvailableSubCommands() {
		b.WriteString("Subcommands:\n\n")
		for _, ch := range c.Commands() {
			if ch.Name() == "help" || ch.Name() == "completion" || ch.Hidden {
				continue
			}
			b.WriteString(fmt.Sprintf("- `%s` — %s\n", ch.Name(), ch.Short))
		}
		b.WriteString("\n")
	}

	if f := c.LocalFlags().FlagUsages(); strings.TrimSpace(f) != "" {
		b.WriteString("Flags:\n\n```\n" + f + "```\n\n")
	}
}
